// Code generated by protoc-gen-go.
// source: keyvalue.proto
// DO NOT EDIT!

/*
Package metrictools is a generated protocol buffer package.

It is generated from these files:
	keyvalue.proto

It has these top-level messages:
	KeyValue
*/
package metrictools

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type KeyValue struct {
	Timestamp        *int64   `protobuf:"fixed64,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Value            *float64 `protobuf:"fixed64,2,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}

func (m *KeyValue) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *KeyValue) GetValue() float64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func init() {
}
